### ISSUE TITLE
No YAML files were found matching your selection.

### ISSUE THREAD

**Issue by aynzayn** [rasshofer/yaml-lint#17]
In version **1.2.1** linter find files by relative path without `./`

In **1.2.2** found nothing. NO RELATIVE, NO FULL PATH

**Comment by rasshofer** [comment]
Can you provide an example of the CLI command and the file/directory tree you’re using? Running something like `yamllint .eslintrc.yml` or `yamllint **/*.yml` should still work.

Are you using Windows by chance? There has been a problem causing `yaml-lint` to not find any files at all on Windows (see #18) that has been fixed with v1.2.3.
