### ISSUE TITLE
After upgrades 1.2.2 does not work on Windows

### ISSUE THREAD

**Issue by A77AY** [rasshofer/yaml-lint#18]
On Windows the problem with full path and `nocase: true`

Does not work with any path

```
Win 10 x64
NTFS
NodeJS 8.9.1
```

**Comment by rasshofer** [comment]
Ooops, thanks a lot for the hint! 🙈 There seems to be a problem (isaacs/node-glob#123) with absolute paths that include a drive letter (e.g. `C:\`) on Windows and `nocase: true` within the [glob library](https://github.com/isaacs/node-glob) used by `yaml-lint` in the background. This is fixed with v1.2.3.
