### ISSUE TITLE
Syntax error near unexpected token

### ISSUE THREAD

**Issue by pesektomas** [rasshofer/yaml-lint#24]
Hello,

when I run command from readme: `yamllint **/*.(yaml|yml)` I got error: `bash: syntax error near unexpected token '('`. Nothing more.

I can't find why this is happening, do you know anyone?

Thank you!

**Comment by pesektomas** [comment]
I think that I can't read the readme file :smile:

**Comment by rasshofer** [comment]
Is this issue still happening and/or relevant? Does the same thing happen if you wrap the glob pattern into quote marks (e.g. `yamllint "**/*.(yaml|yml)"`) to prevent the automated glob pattern expansion? (That expansion takes place before the command is actually run, so it’s not something I can catch/handle in the package. By wrapping the pattern it’s passed as string instead of expanded paths, leaving the expansion to the package itself.)
