### ISSUE TITLE
Glob pattern is not applicated

### ISSUE THREAD

**Issue by pesektomas** [rasshofer/yaml-lint#25]
Hello,

if I run command from readme `yamllint **/*.yml` and tried to debug cli.js I found, that my glob pattern was not applicated. 

I watched on `cli.js` file into this part

```js
(config._ || []).forEach((pattern) => {
  console.log(pattern);
  files = files.concat(glob.sync(path.resolve(process.cwd(), '../packages/**/*.yaml'), {
    dot: true,
    ignore: [].concat(config.ignore).filter(Boolean).map((item) => path.resolve(process.cwd(), item)),
    absolute: true
  }));
});
```

I expected only one console output (my patter `**/*.yml`) but I see list of `*.yml` files with only one level of nested in console. I wanted find all recursive yml files, ale I don't know how, when my pattern is not applicated.

**Comment by JackHowa** [comment]
have the same issue

**Comment by rasshofer** [comment]
Is this issue still happening and/or relevant? Does the same thing happen if you wrap the glob pattern into quote marks (e.g. `yamllint "**/*.(yaml|yml)"`) to prevent the automated glob pattern expansion? (That expansion takes place before the command is actually run, so it’s not something I can catch/handle in the package. By wrapping the pattern it’s passed as string instead of expanded paths, leaving the expansion to the package itself.)
