### ISSUE TITLE
Glob star operator fails to validate lint in macOS 

### ISSUE THREAD

**Issue by vinodhsv** [rasshofer/yaml-lint#27]
Tried to run “yamllint **/*.yml” in macOS and windows but seems like it does not take into account level 2 sub directories in macOS. 
Packaged my yamllint with node and “npm run yamllint **/*.yml”
Please advise if it needs any other syntax for cross platform.

**Comment by rasshofer** [comment]
Is this issue still happening and/or relevant? Does the same thing happen if you wrap the glob pattern into quote marks (e.g. `yamllint "**/*.(yaml|yml)"`) to prevent the automated glob pattern expansion? (That expansion takes place before the command is actually run, so it’s not something I can catch/handle in the package. By wrapping the pattern it’s passed as string instead of expanded paths, leaving the expansion to the package itself.)
